// <auto-generated />
using System;
using JELMusic.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JELMusic.Infrastructure.Migrations
{
    [DbContext(typeof(CoreDbContext))]
    partial class CoreDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("JELMusic.Domain.Entities.MusicalProject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjectVersion")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("MusicalProjects");
                });

            modelBuilder.Entity("JELMusic.Domain.Entities.MusicalProject", b =>
                {
                    b.OwnsOne("JELMusic.Domain.ValueObjects.MusicalDNA", "DNA", b1 =>
                        {
                            b1.Property<Guid>("MusicalProjectId")
                                .HasColumnType("TEXT");

                            b1.HasKey("MusicalProjectId");

                            b1.ToTable("MusicalProjects");

                            b1.WithOwner()
                                .HasForeignKey("MusicalProjectId");

                            b1.OwnsMany("JELMusic.Domain.ValueObjects.MusicalKnowledge.InfluenceProfile", "InfluenceProfiles", b2 =>
                                {
                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("CulturalContext")
                                        .IsRequired()
                                        .HasMaxLength(500)
                                        .HasColumnType("TEXT")
                                        .HasColumnName("CulturalContext");

                                    b2.Property<string>("Description")
                                        .IsRequired()
                                        .HasMaxLength(1000)
                                        .HasColumnType("TEXT")
                                        .HasColumnName("Description");

                                    b2.Property<string>("InfluenceType")
                                        .IsRequired()
                                        .HasMaxLength(200)
                                        .HasColumnType("TEXT")
                                        .HasColumnName("InfluenceType");

                                    b2.Property<string>("MusicalContribution")
                                        .IsRequired()
                                        .HasMaxLength(1000)
                                        .HasColumnType("TEXT")
                                        .HasColumnName("MusicalContribution");

                                    b2.Property<Guid>("MusicalDNAMusicalProjectId")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasMaxLength(200)
                                        .HasColumnType("TEXT")
                                        .HasColumnName("Name");

                                    b2.HasKey("Id");

                                    b2.HasIndex("MusicalDNAMusicalProjectId");

                                    b2.ToTable("InfluenceProfile");

                                    b2.WithOwner()
                                        .HasForeignKey("MusicalDNAMusicalProjectId");

                                    b2.OwnsOne("JELMusic.Domain.ValueObjects.MusicalKnowledge.KnowledgeOrigin", "Origin", b3 =>
                                        {
                                            b3.Property<int>("InfluenceProfileId")
                                                .HasColumnType("INTEGER");

                                            b3.Property<string>("CulturalContext")
                                                .IsRequired()
                                                .HasMaxLength(500)
                                                .HasColumnType("TEXT")
                                                .HasColumnName("OriginCulturalContext");

                                            b3.Property<string>("Reference")
                                                .IsRequired()
                                                .HasMaxLength(500)
                                                .HasColumnType("TEXT")
                                                .HasColumnName("OriginReference");

                                            b3.Property<DateTime>("RegisteredAt")
                                                .HasColumnType("TEXT")
                                                .HasColumnName("OriginRegisteredAt");

                                            b3.Property<string>("Source")
                                                .IsRequired()
                                                .HasMaxLength(200)
                                                .HasColumnType("TEXT")
                                                .HasColumnName("OriginSource");

                                            b3.HasKey("InfluenceProfileId");

                                            b3.ToTable("InfluenceProfile");

                                            b3.WithOwner()
                                                .HasForeignKey("InfluenceProfileId");
                                        });

                                    b2.Navigation("Origin");
                                });

                            b1.OwnsMany("JELMusic.Domain.ValueObjects.MusicalKnowledge.InstrumentProfile", "InstrumentProfiles", b2 =>
                                {
                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("Character")
                                        .IsRequired()
                                        .HasMaxLength(200)
                                        .HasColumnType("TEXT")
                                        .HasColumnName("Character");

                                    b2.Property<string>("CulturalContext")
                                        .IsRequired()
                                        .HasMaxLength(500)
                                        .HasColumnType("TEXT")
                                        .HasColumnName("CulturalContext");

                                    b2.Property<string>("Description")
                                        .IsRequired()
                                        .HasMaxLength(1000)
                                        .HasColumnType("TEXT")
                                        .HasColumnName("Description");

                                    b2.Property<string>("Family")
                                        .IsRequired()
                                        .HasMaxLength(200)
                                        .HasColumnType("TEXT")
                                        .HasColumnName("Family");

                                    b2.Property<string>("Function")
                                        .IsRequired()
                                        .HasMaxLength(500)
                                        .HasColumnType("TEXT")
                                        .HasColumnName("Function");

                                    b2.Property<Guid>("MusicalDNAMusicalProjectId")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasMaxLength(200)
                                        .HasColumnType("TEXT")
                                        .HasColumnName("Name");

                                    b2.HasKey("Id");

                                    b2.HasIndex("MusicalDNAMusicalProjectId");

                                    b2.ToTable("InstrumentProfile");

                                    b2.WithOwner()
                                        .HasForeignKey("MusicalDNAMusicalProjectId");

                                    b2.OwnsOne("JELMusic.Domain.ValueObjects.MusicalKnowledge.KnowledgeOrigin", "Origin", b3 =>
                                        {
                                            b3.Property<int>("InstrumentProfileId")
                                                .HasColumnType("INTEGER");

                                            b3.Property<string>("CulturalContext")
                                                .IsRequired()
                                                .HasMaxLength(500)
                                                .HasColumnType("TEXT")
                                                .HasColumnName("OriginCulturalContext");

                                            b3.Property<string>("Reference")
                                                .IsRequired()
                                                .HasMaxLength(500)
                                                .HasColumnType("TEXT")
                                                .HasColumnName("OriginReference");

                                            b3.Property<DateTime>("RegisteredAt")
                                                .HasColumnType("TEXT")
                                                .HasColumnName("OriginRegisteredAt");

                                            b3.Property<string>("Source")
                                                .IsRequired()
                                                .HasMaxLength(200)
                                                .HasColumnType("TEXT")
                                                .HasColumnName("OriginSource");

                                            b3.HasKey("InstrumentProfileId");

                                            b3.ToTable("InstrumentProfile");

                                            b3.WithOwner()
                                                .HasForeignKey("InstrumentProfileId");
                                        });

                                    b2.Navigation("Origin");
                                });

                            b1.OwnsOne("JELMusic.Domain.ValueObjects.MusicalKnowledge.MusicalStyleProfile", "Style", b2 =>
                                {
                                    b2.Property<Guid>("MusicalDNAMusicalProjectId")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Character")
                                        .IsRequired()
                                        .HasMaxLength(200)
                                        .HasColumnType("TEXT")
                                        .HasColumnName("StyleCharacter");

                                    b2.Property<string>("Characteristics")
                                        .IsRequired()
                                        .HasMaxLength(500)
                                        .HasColumnType("TEXT")
                                        .HasColumnName("StyleCharacteristics");

                                    b2.Property<string>("CulturalContext")
                                        .IsRequired()
                                        .HasMaxLength(500)
                                        .HasColumnType("TEXT")
                                        .HasColumnName("StyleCulturalContext");

                                    b2.Property<string>("Description")
                                        .IsRequired()
                                        .HasMaxLength(1000)
                                        .HasColumnType("TEXT")
                                        .HasColumnName("StyleDescription");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasMaxLength(200)
                                        .HasColumnType("TEXT")
                                        .HasColumnName("StyleName");

                                    b2.HasKey("MusicalDNAMusicalProjectId");

                                    b2.ToTable("MusicalProjects");

                                    b2.WithOwner()
                                        .HasForeignKey("MusicalDNAMusicalProjectId");

                                    b2.OwnsOne("JELMusic.Domain.ValueObjects.MusicalKnowledge.KnowledgeOrigin", "Origin", b3 =>
                                        {
                                            b3.Property<Guid>("MusicalStyleProfileMusicalDNAMusicalProjectId")
                                                .HasColumnType("TEXT");

                                            b3.Property<string>("CulturalContext")
                                                .IsRequired()
                                                .HasMaxLength(500)
                                                .HasColumnType("TEXT")
                                                .HasColumnName("StyleOriginCulturalContext");

                                            b3.Property<string>("Reference")
                                                .IsRequired()
                                                .HasMaxLength(500)
                                                .HasColumnType("TEXT")
                                                .HasColumnName("StyleOriginReference");

                                            b3.Property<DateTime>("RegisteredAt")
                                                .HasColumnType("TEXT")
                                                .HasColumnName("StyleOriginRegisteredAt");

                                            b3.Property<string>("Source")
                                                .IsRequired()
                                                .HasMaxLength(200)
                                                .HasColumnType("TEXT")
                                                .HasColumnName("StyleOriginSource");

                                            b3.HasKey("MusicalStyleProfileMusicalDNAMusicalProjectId");

                                            b3.ToTable("MusicalProjects");

                                            b3.WithOwner()
                                                .HasForeignKey("MusicalStyleProfileMusicalDNAMusicalProjectId");
                                        });

                                    b2.Navigation("Origin");
                                });

                            b1.OwnsOne("JELMusic.Domain.ValueObjects.PerformanceProfile", "Performance", b2 =>
                                {
                                    b2.Property<Guid>("MusicalDNAMusicalProjectId")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Mood")
                                        .IsRequired()
                                        .HasMaxLength(100)
                                        .HasColumnType("TEXT")
                                        .HasColumnName("Mood");

                                    b2.Property<int>("TempoBpm")
                                        .HasColumnType("INTEGER")
                                        .HasColumnName("TempoBpm");

                                    b2.Property<string>("VocalStyle")
                                        .IsRequired()
                                        .HasMaxLength(100)
                                        .HasColumnType("TEXT")
                                        .HasColumnName("VocalStyle");

                                    b2.HasKey("MusicalDNAMusicalProjectId");

                                    b2.ToTable("MusicalProjects");

                                    b2.WithOwner()
                                        .HasForeignKey("MusicalDNAMusicalProjectId");
                                });

                            b1.Navigation("InfluenceProfiles");

                            b1.Navigation("InstrumentProfiles");

                            b1.Navigation("Performance")
                                .IsRequired();

                            b1.Navigation("Style");
                        });

                    b.Navigation("DNA")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
